language: python 
python:
  - 3.5
dist: trusty 
sudo: required
env:
  global:
    - CI_HOME='/home/travis/build/peejayaccts/churchapp_testenv'
    - CI_ROOT='/home/travis/'
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - apache2 
services:
  - mysql 
before_install:
# Use django set-up for database 
  - export DJANGO_SETTINGS_MODULE=config.settings.base
install:
  - pip install -r requirements/base.txt
before_script:
# LOAD DATABASE 
  - mysql -u root -e 'CREATE DATABASE GNT_ChMS_MyDB CHARACTER SET utf8; GRANT ALL ON GNT_ChMS_MyDB.* TO 'pekUrsTruly' IDENTIFIED BY "GloriaTai4ndP#k"';

# RUN the migration and server
  - sudo a2enmod ssl
  - sudo mkdir $CI_ROOT/etc/apache2/ssl
  - cd $CI_HOME/ChMS_project 
  - cd $CI_ROOT/etc/apache2/sites-available/default-ssl.conf
  - pwd
  - python manage.py migrate --noinput
  - python manage.py collectstatic --clear --noinput
  - python manage.py runserver &
# DIRECT TO HOME DIRECOTRY 
  - cd $CI_HOME 
script:  true
