language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
install: 
    "pip install -r requirements.txt"
script: 
  - "python manage.py runserver 0.0.0.0:8000" 
  - "python api_functional_tests.py" 
  - "python functional_tests.py" 
