language: python 
python:
  - 3.5
dist: trusty 
sudo: required
addons:
  apt:
    packages:
#    - mysql-server-5.6
#    - mysql-client-core-5.6
#    - mysql-client-5.6
#    - nodejs
#    - npm 
#    - build-essential 
services:
#  - mysql 
before_install:
# Use django set-up for database 
#  - export DJANGO_SETTINGS_MODULE=config.settings.base
install:
#  - pip install -r requirements/base.txt
before_script:
# Load database 
#  - mysql -u root -e 'CREATE DATABASE GNT_ChMS_MyDB CHARACTER SET utf8; GRANT ALL ON GNT_ChMS_MyDB.* TO 'pekUrsTruly' IDENTIFIED BY "GloriaTai4ndP#k"';

# RUN the migration and server
#  - cd ChMS_project/
#  - python manage.py migrate --noinput
#  - python manage.py runserver &
#  - sleep 3
# RUN the headless UI 
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3
# RUN FRONT END
  - npm install -g npm grunt-cli bower yo generator-karma generator-angular
  - cd churchapp_testenv/ChMS_project/src 
  - npm install
  - bower install
script: 
# RUN the django test script 
  - cd ..
#  - cd ChMS_project/
#  - python api_functional_tests.py
#  - python functional_tests.py
#  - sh ./build.sh
# RUN the grunt build script 
  - sh ./grunt.sh
