language: python 
python:
  - 3.5
dist: trusty 
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
services:
  - mysql 
env:
  - DJANGO_VERSION=1.9.7
before_install:
  - export DJANGO_SETTINGS_MODULE=ChMS.settings.base.py
install:
  - pip install -r requirements/base.txt
before_script:
  - mysql -u root -e 'CREATE DATABASE GNT_ChMS_MyDB CHARACTER SET utf8; GRANT ALL ON GNT_ChMS_MyDB.* TO 'pekUrsTruly' IDENTIFIED BY "GloriaTai4ndP#k"';
  - python manage.py migrate --noinput
script: 
  - python manage.py runserver 
