language: python 
python:
  - 3.5
dist: trusty 
sudo: required
env:
  global:
    - CI_HOME='/home/travis/build/peejayaccts/churchapp_testenv'
addons:
  apt:
    packages:
#    - mysql-server-5.6
#    - mysql-client-core-5.6
#    - mysql-client-5.6
    - nodejs
    - npm 
    - build-essential 
services:
  - mysql 
before_install:
# Use django set-up for database 
#  - export DJANGO_SETTINGS_MODULE=config.settings.base
install:
#  - pip install -r requirements/base.txt
before_script:
# LOAD DATABASE 
#  - mysql -u root -e 'CREATE DATABASE GNT_ChMS_MyDB CHARACTER SET utf8; GRANT ALL ON GNT_ChMS_MyDB.* TO 'pekUrsTruly' IDENTIFIED BY "GloriaTai4ndP#k"';

# RUN the migration and server
#  - cd $CI_HOME/ChMS_project 
#  - python manage.py migrate --noinput
#  - python manage.py runserver &
#  - sleep 3
# RUN the headless UI 
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3
# INSTALL FRONT-END BUILD TOOLS
  - npm install -g grunt-cli bower yo generator-karma generator-angular
  - cd $CI_HOME/ChMS_project/src 
  - npm install
  - bower install
# DIRECT TO HOME DIRECOTRY 
  - cd $CI_HOME 
script: 
# RUN the django test script 
#  - "sh -e ./test-django.sh"
# RUN the grunt build script 
  - "sh -e ./test-grunt.sh"
