language: python 
python:
  - 3.5
dist: trusty 
sudo: required
env:
  global:
    - CI_HOME='/home/travis/build/peejayaccts/churchapp_testenv'
    - CI_ROOT='/home/travis'
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - apache2 
services:
  - mysql 
before_install:
# Use django set-up for database 
  - export DJANGO_SETTINGS_MODULE=config.settings.base
  - which python
  - ls -lh $TRAVIS_BUILD_DIR
  - pwd
install:
  - pip install -r requirements/base.txt
before_script:
  - sudo ls -al /etc/apache2/sites-available/
  - sudo ls -al /etc/apache2/sites-enabled/
  - "sh -e ./apache.sh"
# LOAD DATABASE 
# RUN the migration and server
# DIRECT TO HOME DIRECOTRY 
script:  true
