# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(max_length=255)),
                ('logo_path', models.TextField(blank=True, default='')),
                ('vision', models.TextField(blank=True, default='')),
                ('language_format', models.TextField(blank=True, default='')),
                ('timezone_format', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_initial', models.CharField(blank=True, default='', max_length=1)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married')], default='S', max_length=1)),
                ('is_born_again_christian', models.BooleanField()),
                ('alternate_email_address', models.CharField(blank=True, default='', max_length=250)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Church')),
            ],
        ),
    ]
