# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
