# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 02:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_memberstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='church_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='church',
            name='language_format',
        ),
        migrations.RemoveField(
            model_name='church',
            name='logo_path',
        ),
        migrations.RemoveField(
            model_name='church',
            name='timezone_format',
        ),
        migrations.RemoveField(
            model_name='church',
            name='vision',
        ),
        migrations.AddField(
            model_name='church',
            name='city',
            field=models.CharField(default=datetime.datetime(2016, 8, 5, 2, 35, 16, 840615, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='country',
            field=models.CharField(default=datetime.datetime(2016, 8, 5, 2, 35, 37, 165214, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='date_format',
            field=models.CharField(default=datetime.datetime(2016, 8, 5, 2, 35, 57, 992228, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='language',
            field=models.CharField(default=datetime.datetime(2016, 8, 5, 2, 36, 7, 332272, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='state_province',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='church',
            name='timezone',
            field=models.CharField(default=datetime.datetime(2016, 8, 5, 2, 36, 14, 161671, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='zip_post_code',
            field=models.CharField(default=datetime.datetime(2016, 8, 5, 2, 36, 20, 57986, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
