# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 02:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160805_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='city',
        ),
        migrations.RemoveField(
            model_name='church',
            name='country',
        ),
        migrations.RemoveField(
            model_name='church',
            name='date_format',
        ),
        migrations.RemoveField(
            model_name='church',
            name='language',
        ),
        migrations.RemoveField(
            model_name='church',
            name='state_province',
        ),
        migrations.RemoveField(
            model_name='church',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='church',
            name='zip_post_code',
        ),
        migrations.AddField(
            model_name='church',
            name='banner',
            field=models.CharField(default=datetime.datetime(2016, 8, 5, 2, 41, 34, 564380, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='logo',
            field=models.CharField(default=datetime.datetime(2016, 8, 5, 2, 41, 40, 27293, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='vision',
            field=models.CharField(default=datetime.datetime(2016, 8, 5, 2, 41, 44, 910954, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
