# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160805_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='banner',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='church',
            name='logo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='church',
            name='vision',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
