# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20160807_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='churchregionalinfo',
            old_name='id',
            new_name='church',
        ),
    ]
