# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_person_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchregionalinfo',
            name='church',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='regional_info', serialize=False, to='api.Church'),
        ),
    ]
