# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20160807_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='max_mentees_mentor',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='church',
            name='max_subgroup_members',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='church',
            name='max_subgroup_person',
            field=models.IntegerField(default=3),
        ),
    ]
