# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20160807_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='alternate_email_address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_born_again_christian',
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.CharField(default='asdasdsad', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
