# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20160814_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberStatusList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='church',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Church'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='member_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.MemberStatusList'),
            preserve_default=False,
        ),
    ]
