# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20160815_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contact_info', serialize=False, to='api.Person')),
                ('primary_contact_num', models.CharField(max_length=255)),
                ('other_contact_num', models.CharField(blank=True, max_length=255)),
                ('alternate_email', models.CharField(max_length=255)),
            ],
        ),
    ]
