# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_residentialaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialaddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='residentialaddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
