# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20160815_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialaddress',
            name='state_province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
