# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20160815_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='alternate_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='other_contact_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
