# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_personinterest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personinterest',
            unique_together=set([('person', 'interest')]),
        ),
    ]
