# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20160819_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSkillAndProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
                ('skill_and_profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SkillAndProfession')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='personskillandprofession',
            unique_together=set([('person', 'skill_and_profession')]),
        ),
    ]
