# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20160819_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSpiritualMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
                ('spiritual_milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SpiritualMilestone')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='personspiritualmilestone',
            unique_together=set([('person', 'spiritual_milestone')]),
        ),
    ]
